USE TokuiM
SELECT 
KUNNR AS 得意先コード,
NAME1 AS 得意先名1,
NAME2 AS 得意先名2,
STREET AS 都道府県,
STR_SUPPL2 AS 住所1,
STR_SUPPL3 AS 住所2,
TEL_NUMBER AS TEL,
FAX_NUMBER AS FAX,
VKBUR AS 営業所コード,
VKBURMEI AS 営業所,
PERNR AS 営業員,
PERNRMEI AS 営業員名,
KUNN2B AS 請求先,
KUNN2BMEI AS 請求先名
FROM T_tokuiM1
INNER JOIN T_tokuiM2
ON T_tokuiM2.KUNNR2 = T_tokuiM1.KUNNR
WHERE NAME1 LIKE '%丸紅%'　AND
NOT (NAME1 LIKE '%削除%' OR NAME1 LIKE '%使用禁止%')